version: '3'
services:
 mongodb:
   image: mongo:3.3
   volumes:
    - db_data:/data/db
   environment:
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   image: teamcloudyuga/rsvpapp:mooc
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
   networks:
    - rsvpnet

networks:
 rsvpnet:

volumes:
 db_data:

